[versions]
current = "0.1.0"
jvm = "17"
benmanes-versions = "0.53.0"
kotlin = "2.3.0"
detekt = "1.23.8"
kotlin-datetime = "0.7.1"
kotlinx-browser = "2025.12.6"
kastro = "0.5.0"
kotlinx-html = "0.11.0"
kotlinx-coroutines = "1.10.2"
svg-magick = "0.1.0"
statik = "0.1.0"

[libraries]
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlin-datetime" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
kastro = { module = "dev.jamesyox:kastro", version.ref = "kastro" }
kotlinx-html = { module = "org.jetbrains.kotlinx:kotlinx-html", version.ref = "kotlinx-html" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlin-js-browser = { module = "org.jetbrains.kotlin-wrappers:kotlin-browser", version.ref = "kotlinx-browser" }

jamesyox-svgMagick = { module = "dev.jamesyox:svgk", version.ref = "svg-magick" }
jamesyox-statik = { module = "dev.jamesyox:statik-core", version.ref = "statik" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
benmanes-versions = { id = "com.github.ben-manes.versions", version.ref = "benmanes-versions" }
